/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AISidebar: typeof import('./src/components/ai/AISidebar.vue')['default']
    BimPreview: typeof import('./src/components/preview/BimPreview.vue')['default']
    CadPreview: typeof import('./src/components/preview/CadPreview.vue')['default']
    CustomExtract: typeof import('./src/components/ai/CustomExtract.vue')['default']
    ExtractHistory: typeof import('./src/components/ai/ExtractHistory.vue')['default']
    ExtractTemplateManager: typeof import('./src/components/ai/ExtractTemplateManager.vue')['default']
    FileViewer: typeof import('./src/components/core/FileViewer.vue')['default']
    ImagePreview: typeof import('./src/components/preview/ImagePreview.vue')['default']
    OfficePreview: typeof import('./src/components/preview/OfficePreview.vue')['default']
    PdfPreview: typeof import('./src/components/preview/PdfPreview.vue')['default']
    TextPreview: typeof import('./src/components/preview/TextPreview.vue')['default']
    VideoPreview: typeof import('./src/components/preview/VideoPreview.vue')['default']
    XmindPreview: typeof import('./src/components/preview/XmindPreview.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
